# Generated by Django 3.2.3 on 2021-05-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='CategirieProfessionnelle',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='DemandeAMM',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='Duré de conservation',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='Fabriquant',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='Forme galinique',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='Libellé',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='Nature',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='NomCommerciale',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='PubliqueCible',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='VoiAdministration',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='date_creation',
        ),
    ]
