# Generated by Django 3.2.3 on 2021-05-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renouvellement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Renouvellement',
        ),
    ]
