# Generated by Django 3.2.3 on 2021-05-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renouvellement', '0002_auto_20210520_0129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Renouvellement',
        ),
    ]
