# Generated by Django 3.2.3 on 2021-05-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('idComposition', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=200, null=True)),
                ('classeTerapeutique', models.CharField(max_length=200, null=True)),
                ('dosage', models.CharField(max_length=200, null=True)),
                ('unite', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
